name: Python Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # 3. Install dependencies using Makefile
      - name: Install dependencies
        run: |
          make install

      # 4. Run the application in the background and save the PID
      - name: Run the application
        run: |
          make run &  # Start Flask server on port 3000 in the background
          echo $! > flask_pid.txt  # Save the Process ID (PID) to a file
          sleep 15  # Allow more time for server to start

      # 5. Check if the server is running (on port 3000)
      - name: Check if server is running
        run: |
          curl --fail http://localhost:3000 || exit 1

      # 6. Terminate the background Flask process using the PID
      - name: Stop Flask server
        run: |
          kill $(cat flask_pid.txt) || echo "No process to kill"

      # 7. Lint the code with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,__pycache__,.git
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv,__pycache__,.git
